### ISSUE TITLE
realtime-xavm.plgz file is missing

### ISSUE THREAD

**Issue by michaelpatzer** [PushSpring/PushSpringSDK-iOS#2]
The file "realtime-xavm.plgz" is referenced from the PushSpringSample project, but the file is missing from the PushSpringSDK directory. This prevents the sample app from being built.

Removing the file allows the target to build, but an exception is immediately thrown. This line of the stack trace tells me that the exception is probably related to this missing file: [PSNetworkEngine _loadIncludedRealtimeXavmDb]

Here is the output of the call stack at the time of the exception:
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'data parameter is nil'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000110139f35 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x000000010fc3dbb7 objc_exception_throw + 45
	2   CoreFoundation                      0x0000000110139e6d +[NSException raise:format:] + 205
	3   Foundation                          0x000000010f578732 +[NSPropertyListSerialization propertyListWithData:options:format:error:] + 67
	4   PushSpringSample                    0x000000010de78fb5 -[PSNetworkEngine _loadIncludedRealtimeXavmDb] + 533
	5   PushSpringSample                    0x000000010de73f45 -[PSNetworkEngine getRealtimeCustomerInsights:andCompletionHandler:] + 101
	6   PushSpringSample                    0x000000010de80072 -[PushSpring getRealtimeCustomerInsights:] + 130
	7   PushSpringSample                    0x000000010de71bd6 -[AppDelegate application:didFinishLaunchingWithOptions:] + 998
	8   UIKit                               0x000000010e29e475 -[UIApplication _handleDelegateCallbacksWithOptions:isSuspended:restoreState:] + 234
	9   UIKit                               0x000000010e29efbc -[UIApplication _callInitializationDelegatesForMainScene:transitionContext:] + 2463
	10  UIKit                               0x000000010e2a1d2c -[UIApplication _runWithMainScene:transitionContext:completion:] + 1350
	11  UIKit                               0x000000010e2a0bf2 -[UIApplication workspaceDidEndTransaction:] + 179
	12  FrontBoardServices                  0x0000000112bab2a3 __31-[FBSSerialQueue performAsync:]_block_invoke + 16
	13  CoreFoundation                      0x000000011006f53c __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ + 12
	14  CoreFoundation                      0x0000000110065285 __CFRunLoopDoBlocks + 341
	15  CoreFoundation                      0x0000000110065045 __CFRunLoopRun + 2389
	16  CoreFoundation                      0x0000000110064486 CFRunLoopRunSpecific + 470
	17  UIKit                               0x000000010e2a0669 -[UIApplication _run] + 413
	18  UIKit                               0x000000010e2a3420 UIApplicationMain + 1282
	19  PushSpringSample                    0x000000010de717c3 main + 115
	20  libdyld.dylib                       0x000000011147d145 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by chriskinsman** [comment]
Sorry about that.  I have dropped a new release 1.1.4 that includes the file.

**Comment by michaelpatzer** [comment]
Thanks! That resolved the issue; the sample app now builds.
